USE master
GO;
ALTER DATABASE orion_ve
ADD FILEGROUP FG_CDC;
GO
ALTER DATABASE orion_ve
ADD FILE 
(    NAME = FL_CDC_01,FILENAME = 'E:\MSSQL10_50.ORIONCORE\MSSQL\DATA\orion_ve\FL_CDC_01.ndf',
    SIZE = 5MB,FILEGROWTH = 5MB),
(   NAME = FL_CDC_02,FILENAME = 'E:\MSSQL10_50.ORIONCORE\MSSQL\DATA\orion_ve\FL_CDC_02.ndf',
    SIZE = 5MB,FILEGROWTH = 5MB),
(   NAME = FL_CDC_03,FILENAME = 'E:\MSSQL10_50.ORIONCORE\MSSQL\DATA\orion_ve\FL_CDC_03.ndf',
    SIZE = 5MB, FILEGROWTH = 5MB),
(   NAME = FL_CDC_04,
    FILENAME = 'E:\MSSQL10_50.ORIONCORE\MSSQL\DATA\orion_ve\FL_CDC_04.ndf',
    SIZE = 5MB, FILEGROWTH = 5MB)
TO FILEGROUP FG_CDC;
GO
