USE [master]
GO
CREATE DATABASE [DW_Work]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Work', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Work.mdf' , SIZE = 20725760KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB ), 
 FILEGROUP [data]  DEFAULT
( NAME = N'data', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Work_data.mdf' , SIZE = 39838720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [index] 
( NAME = N'index', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Work_index.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW_Work_log', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Work_log.ldf' , SIZE = 263168KB , MAXSIZE = 2048GB , FILEGROWTH = 262144KB )
GO
ALTER DATABASE [DW_Work] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Work].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DW_Work] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DW_Work] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DW_Work] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DW_Work] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DW_Work] SET ARITHABORT OFF 
GO
ALTER DATABASE [DW_Work] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DW_Work] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DW_Work] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DW_Work] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DW_Work] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DW_Work] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DW_Work] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DW_Work] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DW_Work] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DW_Work] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DW_Work] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DW_Work] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DW_Work] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DW_Work] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DW_Work] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DW_Work] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DW_Work] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DW_Work] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DW_Work] SET  MULTI_USER 
GO
ALTER DATABASE [DW_Work] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DW_Work] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DW_Work] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DW_Work] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DW_Work] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DW_Work', N'ON'
GO
ALTER DATABASE [DW_Work] SET  READ_WRITE 
GO
