USE [dba_admin]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[usp_LoadVolumeSpace] 
AS

-- Lumo Energy | Database Administration
-- Load disk volume size and used data generated by powershell wmi command
--
-- 2012-10-11 Darren.Pilkington Initial Release
--

SET NOCOUNT ON

BULK INSERT [dba_admin].[dbo].[VolumeSpaceLoad]
FROM 'c:\dba_admin\volume_space.dat'
WITH
(
DATAFILETYPE = 'char',
FIELDTERMINATOR = ',',
FIRSTROW = 2
);

INSERT INTO [dba_admin].[dbo].[VolumeSpace] (volume_name, capacity_bytes, freespace_bytes)
SELECT
		RTRIM(REPLACE([volume_name],'"','')),
		CONVERT(bigint,REPLACE([capacity_bytes],'"','')),
		CONVERT(bigint,REPLACE([freespace_bytes],'"',''))
FROM [dba_admin].[dbo].[VolumeSpaceLoad];

TRUNCATE TABLE [dba_admin].[dbo].[VolumeSpaceLoad];
GO
