USE [master]
GO
CREATE DATABASE [DW_Utility]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Utility', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Utility.mdf' , SIZE = 35840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [data]  DEFAULT
( NAME = N'data', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Utility_data.mdf' , SIZE = 46080KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [index] 
( NAME = N'index', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Utility_index.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW_Utility_log', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Utility_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO
ALTER DATABASE [DW_Utility] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Utility].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DW_Utility] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DW_Utility] SET ARITHABORT OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DW_Utility] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DW_Utility] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DW_Utility] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DW_Utility] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DW_Utility] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DW_Utility] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DW_Utility] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DW_Utility] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DW_Utility] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DW_Utility] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DW_Utility] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DW_Utility] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DW_Utility] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DW_Utility] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DW_Utility] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DW_Utility] SET  MULTI_USER 
GO
ALTER DATABASE [DW_Utility] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DW_Utility] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DW_Utility] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DW_Utility] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DW_Utility] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DW_Utility', N'ON'
GO
ALTER DATABASE [DW_Utility] SET  READ_WRITE 
GO
USE [master]
GO
CREATE DATABASE [DW_Utility]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Utility', FILENAME = N'F:\MSSQL12.SQLSTG1\MSSQL\DATA\DW_Utility.mdf' , SIZE = 81920KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [data]  DEFAULT
( NAME = N'data', FILENAME = N'F:\MSSQL12.SQLSTG1\MSSQL\DATA\DW_Utility_data.mdf' , SIZE = 87040KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [index] 
( NAME = N'index', FILENAME = N'F:\MSSQL12.SQLSTG1\MSSQL\DATA\DW_Utility_index.mdf' , SIZE = 35840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW_Utility_log', FILENAME = N'J:\MSSQL12.SQLSTG1\MSSQL\Data\DW_Utility_log.ldf' , SIZE = 30720KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO
ALTER DATABASE [DW_Utility] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Utility].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DW_Utility] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DW_Utility] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DW_Utility] SET ARITHABORT OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DW_Utility] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DW_Utility] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DW_Utility] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DW_Utility] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DW_Utility] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DW_Utility] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DW_Utility] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DW_Utility] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DW_Utility] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DW_Utility] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DW_Utility] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DW_Utility] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DW_Utility] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DW_Utility] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DW_Utility] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DW_Utility] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DW_Utility] SET  MULTI_USER 
GO
ALTER DATABASE [DW_Utility] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DW_Utility] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DW_Utility] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DW_Utility] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DW_Utility] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DW_Utility', N'ON'
GO
ALTER DATABASE [DW_Utility] SET  READ_WRITE 
GO
