USE [master]
GO
CREATE DATABASE [DW_Staging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Staging', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Staging.mdf' , SIZE = 208083648KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [data]  DEFAULT
( NAME = N'data', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Staging_data.mdf' , SIZE = 177054720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [index] 
( NAME = N'index', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Staging_index.mdf' , SIZE = 276495360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW_Staging_log', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Staging_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO
ALTER DATABASE [DW_Staging] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Staging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DW_Staging] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DW_Staging] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DW_Staging] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DW_Staging] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DW_Staging] SET ARITHABORT OFF 
GO
ALTER DATABASE [DW_Staging] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DW_Staging] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DW_Staging] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DW_Staging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DW_Staging] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DW_Staging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DW_Staging] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DW_Staging] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DW_Staging] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DW_Staging] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DW_Staging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DW_Staging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DW_Staging] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DW_Staging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DW_Staging] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DW_Staging] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DW_Staging] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DW_Staging] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DW_Staging] SET  MULTI_USER 
GO
ALTER DATABASE [DW_Staging] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DW_Staging] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DW_Staging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DW_Staging] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DW_Staging] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DW_Staging', N'ON'
GO
ALTER DATABASE [DW_Staging] SET  READ_WRITE 
GO
