USE [DW_Staging]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [orion_temp].[nc_client](
	[seq_party_id] [numeric](18, 0) NULL,
	[seq_comp_type_id] [numeric](18, 0) NULL,
	[seq_industry_id] [numeric](18, 0) NULL,
	[seq_client_priority_id] [numeric](18, 0) NULL,
	[seq_pay_method_id] [numeric](18, 0) NULL,
	[seq_bill_cycle_id] [numeric](18, 0) NULL,
	[seq_int_crd_chk_id] [numeric](18, 0) NULL,
	[seq_inv_del_mode_id] [numeric](18, 0) NULL,
	[seq_inv_style_id] [numeric](18, 0) NULL,
	[seq_tax_ind_id] [numeric](18, 0) NULL,
	[password] [varchar](10) NULL,
	[employer] [varchar](100) NULL,
	[employer_ph_no] [varchar](20) NULL,
	[alert] [varchar](max) NULL,
	[estimate_date] [datetime] NULL,
	[auck_employ] [numeric](6, 0) NULL,
	[nz_employ] [numeric](6, 0) NULL,
	[annual_sale] [numeric](19, 0) NULL,
	[mobile_user] [numeric](4, 0) NULL,
	[connect_call] [datetime] NULL,
	[credit_reseller_flag] [char](1) NULL,
	[date_received] [datetime] NULL,
	[seq_staff_id] [numeric](18, 0) NULL,
	[credit_limit] [money] NULL,
	[stop_credit_flag] [char](1) NULL,
	[bank] [varchar](20) NULL,
	[bank_branch] [varchar](20) NULL,
	[bank_account_no] [varchar](18) NULL,
	[credit_card_name] [varchar](100) NULL,
	[credit_card_no] [varchar](8000) NULL,
	[credit_card_expiry] [varchar](5) NULL,
	[bill_notes] [varchar](max) NULL,
	[prompt_payment_discount] [numeric](6, 3) NULL,
	[avg_monthly_spend] [money] NULL,
	[active] [char](1) NULL,
	[insert_datetime] [datetime] NULL,
	[insert_user] [varchar](20) NULL,
	[insert_process] [varchar](20) NULL,
	[update_datetime] [datetime] NULL,
	[update_user] [varchar](20) NULL,
	[update_process] [varchar](20) NULL,
	[tcnz_lookup_performed] [varchar](1) NULL,
	[additional_svce_0800] [char](1) NULL,
	[additional_svce_ccard] [char](1) NULL,
	[additional_svce_power] [char](1) NULL,
	[additional_svce_tolls] [char](1) NULL,
	[seq_pcms_int_status_id] [numeric](18, 0) NULL,
	[calling_card_reseller] [varchar](1) NULL,
	[seq_deliver_class_id] [numeric](18, 0) NULL,
	[deliver_class_automatic] [char](1) NULL,
	[deliver_class_note] [varchar](max) NULL,
	[invoice_message] [varchar](max) NULL,
	[message_view_inv_run_id] [numeric](18, 0) NULL,
	[seq_credit_status_id] [numeric](18, 0) NULL,
	[source_of_income] [varchar](100) NULL,
	[user_defined_1] [varchar](100) NULL,
	[user_defined_2] [varchar](100) NULL,
	[user_defined_3] [varchar](100) NULL,
	[bond] [money] NULL,
	[credit_card_type_code] [varchar](20) NULL,
	[credit_card_verif_no] [varchar](4) NULL,
	[pull_bill_custom_dir] [varchar](100) NULL,
	[pull_bill_expiry_date] [datetime] NULL,
	[treat_type_id] [numeric](18, 0) NULL,
	[customer_prospect] [varchar](10) NULL,
	[alert_expires] [char](1) NULL,
	[alert_expiry_date] [datetime] NULL,
	[promo_allowed] [varchar](1) NULL,
	[district_id] [numeric](18, 0) NULL,
	[dd_hold_start_date] [datetime] NULL,
	[dd_hold_end_date] [datetime] NULL,
	[bank_account_name] [varchar](100) NULL,
	[air_con] [varchar](1) NULL,
	[elec_pool_heating] [varchar](1) NULL,
	[under_floor_heating] [varchar](1) NULL,
	[referral_check] [varchar](1) NULL,
	[dc_acc_id] [varchar](40) NULL,
	[occupier_code] [varchar](10) NULL,
	[oss_login] [varchar](100) NULL,
	[oss_pass] [varchar](20) NULL,
	[medicard_no] [varchar](20) NULL,
	[alt_email_address] [varchar](100) NULL,
	[inv_message_start_date] [datetime] NULL,
	[inv_message_end_date] [datetime] NULL,
	[inv_message_invoice_id] [numeric](18, 0) NULL,
	[inv_message_display_type] [varchar](20) NULL,
	[inv_due_days] [numeric](18, 0) NULL,
	[cc_pen_points] [numeric](18, 0) NULL,
	[loyalty_id] [numeric](18, 0) NULL,
	[oss_pass_change] [varchar](1) NULL,
	[oss_pass_change_count] [numeric](18, 0) NULL,
	[cz_registered] [varchar](1) NULL,
	[caf_tariff_code] [varchar](20) NULL,
	[oss_receive_email_flag] [varchar](1) NULL,
	[oss_pass2] [varbinary](8000) NULL,
	[smartbill_cpull_id] [numeric](18, 0) NULL,
	[user_defined_4] [varchar](100) NULL,
	[oss_login_count] [int] NULL,
	[debtor_insured] [varchar](1) NULL,
	[credit_limit_imposed] [varchar](1) NULL,
	[court_location_id] [numeric](18, 0) NULL,
	[membership_no] [varchar](100) NULL,
	[smartbill_include_yn] [varchar](1) NULL,
	[encrypt_credit_card_no] [varbinary](2000) NULL,
	[due_date_fixed_day_of_month] [varchar](1) NULL,
	[DCA_reference_id] [varchar](50) NULL,
	[credit_agency_reference_id] [varchar](50) NULL,
	[referral_type] [varchar](20) NULL,
	[referral_type_notes] [varchar](2000) NULL,
	[referral_seq_cmpgn_id] [numeric](18, 0) NULL,
	[ref_seq_party_id] [numeric](18, 0) NULL,
	[referral_created_yn] [varchar](1) NULL,
	[cc_profile_id] [numeric](18, 0) NULL,
	[cc_payment_profile_id] [numeric](18, 0) NULL,
	[credit_score] [numeric](18, 0) NULL,
	[credit_score_datetime] [datetime] NULL,
	[credit_card_post_code] [varchar](10) NULL,
	[tou_site] [char](1) NULL,
	[virgin_member_id] [varchar](10) NULL,
	[group_home] [varchar](1) NULL,
	[auto_login_datetime] [datetime] NULL,
	[auto_login_code] [varchar](200) NULL,
	[openid_login_code] [varchar](50) NULL,
	[credit_card_token] [varchar](100) NULL,
	[Meta_LatestUpdate_TaskExecutionInstanceId] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
