USE [master]
GO
CREATE DATABASE [dba_admin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dba_admin', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\Data\dba_admin.mdf' , SIZE = 27648KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dba_admin_log', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\Data\dba_admin.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO
ALTER DATABASE [dba_admin] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dba_admin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dba_admin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dba_admin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dba_admin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dba_admin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dba_admin] SET ARITHABORT OFF 
GO
ALTER DATABASE [dba_admin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dba_admin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dba_admin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dba_admin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dba_admin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dba_admin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dba_admin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dba_admin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dba_admin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dba_admin] SET  ENABLE_BROKER 
GO
ALTER DATABASE [dba_admin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dba_admin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dba_admin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dba_admin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dba_admin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dba_admin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dba_admin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dba_admin] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dba_admin] SET  MULTI_USER 
GO
ALTER DATABASE [dba_admin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dba_admin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dba_admin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dba_admin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [dba_admin] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'dba_admin', N'ON'
GO
ALTER DATABASE [dba_admin] SET  READ_WRITE 
GO
