USE [master]
GO
CREATE DATABASE [DW_Access]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_Access', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Access.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [data]  DEFAULT
( NAME = N'data', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Access_data.mdf' , SIZE = 25600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [index] 
( NAME = N'index', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Access_index.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DW_Access_log', FILENAME = N'E:\MSSQL12.SQLDEV1\MSSQL\DATA\DW_Access_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO
ALTER DATABASE [DW_Access] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_Access].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DW_Access] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DW_Access] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DW_Access] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DW_Access] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DW_Access] SET ARITHABORT OFF 
GO
ALTER DATABASE [DW_Access] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DW_Access] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DW_Access] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DW_Access] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DW_Access] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DW_Access] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DW_Access] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DW_Access] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DW_Access] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DW_Access] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DW_Access] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DW_Access] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DW_Access] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DW_Access] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DW_Access] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DW_Access] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DW_Access] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DW_Access] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DW_Access] SET  MULTI_USER 
GO
ALTER DATABASE [DW_Access] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DW_Access] SET DB_CHAINING ON 
GO
ALTER DATABASE [DW_Access] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DW_Access] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DW_Access] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DW_Access', N'ON'
GO
ALTER DATABASE [DW_Access] SET  READ_WRITE 
GO
