CREATE TABLE [Views].[UnbilledRevenueReport](
[FinancialMonth] [tinyint] NULL,
	[ReportDate] [date] NULL,
	[AccountingPeriod] [int] NULL,
	[AccountNumber] [int] NULL,
	[CustomerName] [nvarchar](100) NULL,
	[CustomerType] [nchar](11) NULL,
	[ContractStatus] [nchar](10) NULL,
	[BillingCycle] [nchar](10) NULL,
	[TNICode] [nvarchar](20) NULL,
	[TransmissionLossFactor] [decimal](25, 15) NULL,
	[DistrictState] [nchar](3) NULL,
	[MarketIdentifier] [nvarchar](30) NULL,
	[ServiceStatus] [nvarchar](30) NULL,
	[ServiceActiveStartDate] [date] NULL,
	[ServiceActiveEndDate] [date] NULL,
	[FRMPStartDate] [date] NULL,
	[ContractTerminatedDate] [date] NULL,
	[FuelType] [nvarchar](11) NULL,
	[SiteMeteringType] [nchar](6) NULL,
	[ServiceState] [nchar](3) NULL,
	[SiteEDC] [decimal](18, 6) NULL,
	[DLF] [decimal](6, 4) NULL,
	[MeterRegisterEDC] [decimal](18, 6) NULL,
	[MeterMarketSerialNumber] [nvarchar](50) NULL,
	[MeterRegisterKey] [int] NULL,
	[MeterSystemSerialNumber] [nvarchar](50) NULL,
	[RegisterMultiplier] [decimal](18, 6) NULL,
	[MeterRegisterBillingTypeCode] [nvarchar](100) NULL,
	[MeterRegisterReadDirection] [nchar](6) NULL,
	[MeterRegisterSystemIdentifier] [nchar](10) NULL,
	[MeterRegisterStatus] [nchar](8) NULL,
	[MeterRegisterActiveStartDate] [date] NULL,
	[MeterRegisterActiveEndDate] [date] NULL,
	[NetworkTariffCode] [nvarchar](20) NULL,
	[LastBilledRead] [decimal](18, 4) NULL,
	[LastBilledReadDate] [date] NULL,
	[ScheduleType] [nchar](5) NULL,
	[FixedTariffAdjustment] [decimal](5, 4) NULL,
	[VariableTariffAdjustment] [decimal](5, 4) NULL,
	[PricePlanStartDate] [date] NULL,
	[PricePlanEndDate] [date] NULL,
	[PricePlanCode] [nvarchar](20) NULL,
	[BundledFlag] [nvarchar](11) NULL,
	[PriceStep1] [money] NULL,
	[PriceStep2] [money] NULL,
	[PriceStep3] [money] NULL,
	[PriceStep4] [money] NULL,
	[PriceStep5] [money] NULL,
	[UnitStep1] [decimal](18, 7) NULL,
	[UnitStep2] [decimal](18, 7) NULL,
	[UnitStep3] [decimal](18, 7) NULL,
	[UnitStep4] [decimal](18, 7) NULL,
	[UnbilledFromDate] [date] NULL,
	[UnbilledToDate] [date] NULL,
	[UnbilledDays] [int] NULL,
	[SettlementUsageEndDate] [date] NULL,
	[SettlementUsage] [decimal](18, 7) NULL,
	[EstimatedUsage] [decimal](18, 7) NULL,
	[TotalUnbilledUsage] [decimal](18, 7) NULL,
	[TotalUnbilledRevenue] [money] NULL,
	[LastBilledReadType] [nchar](9) NULL,
	[EstimatedUsageEndDate] [date] NULL,
	[BilledEstimatedDays] [int] NULL,
	[BilledEstimatedUsage] [decimal](18, 7) NULL,
	[BilledEstimatedRevenue] [money] NULL,
	[LastBilledActualRead] [decimal](18, 4) NULL,
	[LastBilledActualReadDate] [date] NULL,
	[Meta_Insert_TaskExecutionInstanceId] [int] NOT NULL
) ON [data]

GO

CREATE CLUSTERED COLUMNSTORE INDEX [ClusteredColumnStoreIndex-UnbilledRevenueReport] ON [Views].[UnbilledRevenueReport] WITH (DROP_EXISTING = OFF)
GO